# Generated by Django 4.0.2 on 2022-06-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsman', '0002_alter_news_slug_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
